### ISSUE TITLE
dub icon needed

### ISSUE THREAD

**Issue by BBasile** [D-Programming-Language/dub-registry#120]
Can someone provide a 16*16 icon for DUB ?

something better than 
![dub_small](https://cloud.githubusercontent.com/assets/7805501/9976151/dc7dd37a-5eda-11e5-9a9a-f7b82fd58f30.png)

but still with a transparent background.

**Comment by s-ludwig** [comment]
Fastest method would be to extract the 16x16 version from http://code.dlang.org/favicon.ico

**Comment by s-ludwig** [comment]
Oh, you wanted to remove the dark background... but it's part of the logo. Maybe a mixture between the colored and black and white version? 
![dub16t](https://cloud.githubusercontent.com/assets/1645969/9979435/0e945d38-5f6d-11e5-9b33-d9c644ad767d.png)

Otherwise, this would be the official 16x16 logo (with transparent stripes at the to and bottom): 
![dub16](https://cloud.githubusercontent.com/assets/1645969/9979438/1ca50f6c-5f6d-11e5-875a-292b256e3c26.png)


BTW, I've started to draft a new logo that I want to finish some time. It fits better with the D logo in terms of color, and better with the logos of other package managers in terms of dimensions.

**Comment by BBasile** [comment]
Thx. By te way I'd like to inform you that the link to SDLang description is dead (the link in http://code.dlang.org/package-format?lang=sdl, not this page itself).

http://sdl.ikayzo.org/

**Comment by s-ludwig** [comment]
Yeah, the page is down for a while now (although the error has changed now). @Abscissa has already informed the author,

**Comment by Abscissa** [comment]
FWIW, I've put up a mirror here:
http://semitwist.com/sdl-mirror/Home.html

I intend for that mirror to be permanently available.
