### ISSUE TITLE
subpackages are virtually invisible

### ISSUE THREAD

**Issue by adamdruppe** [D-Programming-Language/dub-registry#123]
I'm not a big fan of dub's model of separate github repositories per item, since I prefer to organize on the module level instead. Under community pressure though, I've started looking at ways to make dub work for me and subpackages seem to be the best option.

The problem is that subpackages are almost invisible on the code.dlang.org site! The listing doesn't show them, the search doesn't find them, the instructions on a package don't mention them, and the description field is too small to document it myself.

I propose that subpackages be parsed by the directory and listed the same as top-level packages, or, at the very least, listed when you click a top level package with instructions and descriptions on that page, with search scanning subpackages and bringing you to that package as well when it comes up.

**Comment by MartinNowak** [comment]
What about http://code.dlang.org/packages/gfm, it lists all the subpackages as dependencies?

**Comment by s-ludwig** [comment]
Yes, that's a common pattern that you make the base package `"targetType": "none"` and let it depend on all of the sub packages, so that people can opt to just depend on the base package and then automatically get all of the sub packages.

But of course we should still list sub packages properly - after all they have their own description, dependencies etc. The only reason why I haven't implemented this is because I haven't yet split up vibe.d into sub packages and thus didn't have a use for it so far. I'll have a look at both soon.
