### ISSUE TITLE
stats.json doesn't work

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub-registry#94]
Just tried the newly added stats.json functionality.
http://code.dlang.org/api/packages/bloom/stats.json
http://code.dlang.org/api/packages/bloom/0.2.1/stats.json

Only get an error about an aggregation failure.
```
object.Exception@../vibe/source/vibe/db/mongo/collection.d(281): Aggregate command failed.
```

Trying the same on my staging site works, so I guess `code.dlang.org` is still using a 2.4 version of MongoDB that doesn't support [`$literal`](http://docs.mongodb.org/manual/reference/operator/aggregation/literal/).
https://dub.staging.dawg.eu/api/packages/bloom/stats.json
https://dub.staging.dawg.eu/api/packages/bloom/0.2.1/stats.json

**Comment by MartinNowak** [comment]
@s-ludwig would it be possible to update MongoDB?
http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/

**Comment by MartinNowak** [comment]
Ping @s-ludwig, how about now? I want to provide a nice shield people can put onto their projects, see #96.

**Comment by s-ludwig** [comment]
Sorry Martin, this went past me. I'll update the DB right away.

**Comment by s-ludwig** [comment]
Should be good to go now (3.0.1).

**Comment by MartinNowak** [comment]
Bleeding edge, let me know if things work out for you. I resisted to update to 3.x on production services for now.

**Comment by s-ludwig** [comment]
Yeah, since the old APT repository just had 2.4.x in it, I followed the current installation instructions which are for 3.x. There also seems to be a 2.6.x repository somewhere, but I couldn't be bothered to search through their wiki. However, there are in fact compatibility issues ([forum.rejectedsoftware.com](http://forum.rejectedsoftware.com) is broken), so I'll probably just downgrade to 2.6 anyway.

**Comment by s-ludwig** [comment]
Back working now with 2.6.8.
